### ISSUE TITLE
creating telephony data

### ISSUE THREAD

**Issue by dhecloud** [zjc6666/Accent-Recognition#3]
Hi! I am trying to create telephony data using your script `add-codec/add-codec.sh`.

Can I ask where to get these files? These were in the script but I couldn't find it in the repo
1. `utils/data/get_utt2dur.sh`
2. `utils/data/resample_data_dir.sh`
3. `utils/data/copy_data_dir.sh` same as `scripts/copy_data_dir.sh`?

Thank you!

**Comment by zjc6666** [comment]
These three files are all from the utils directory of Kaldi, so they are not uploaded.
You all can find it in this link : https://github.com/kaldi-asr/kaldi/tree/master/egs/wsj/s5/utils
